spring:
  application:
    name: grim
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/grim?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${GRIM_MYSQL_USER}
    password: ${GRIM_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  hibernate:
    ddl-auto: update
  sql:
    init:
      mode: always
  # profile:
    # include: oauth, mail, s3, payments
  data:
    redis:
    host: localhost
    port: 6379
  # include: oauth
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080